version: "2"

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - modernize
    - nakedret
    - nestif
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - captLocal
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: exported
          disabled: true
    misspell:
      locale: US
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 30
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 5
  exclusions:
    generated: strict
    paths:
      - vendor
      - mocks
      - dist
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - unparam
          - goconst
          - gocyclo

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/projecteru2/cocoon

