package types

import "time"

// SnapshotConfig carries the parameters for creating a snapshot.
// The hypervisor fills ID, Image, ImageBlobIDs, and resource fields; the CLI adds Name and Description.
type SnapshotConfig struct {
	ID           string              `json:"id,omitempty"` // generated by the hypervisor during Snapshot()
	Name         string              `json:"name"`
	Description  string              `json:"description,omitempty"`
	Image        string              `json:"image,omitempty"`          // source image reference (e.g. "ubuntu:22.04")
	ImageBlobIDs map[string]struct{} `json:"image_blob_ids,omitempty"` // blob hex set for GC pinning

	// Original VM resource config, populated during snapshot creation.
	// Used by clone for parameter inheritance and validation.
	CPU     int   `json:"cpu,omitempty"`
	Memory  int64 `json:"memory,omitempty"`  // bytes
	Storage int64 `json:"storage,omitempty"` // bytes
	NICs    int   `json:"nics,omitempty"`
}

// Snapshot is the public record for a snapshot.
type Snapshot struct {
	SnapshotConfig
	CreatedAt time.Time `json:"created_at"`
}
